### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 85: ordinal not in range(256)

### ISSUE THREAD

**Issue by robputt** [robputt796/ThisIsScraper#1]
2017-12-20 13:23:07,910 DEBUG: http://www.plymouthherald.co.uk:80 "GET /news/plymouth-news/hms-ocean-home-whats-next-952279 HTTP/1.1" 200 33602
/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/sql/sqltypes.py:219: SAWarning: Unicode type received non-unicode bind param value "b'Christmas came early for '...". (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
Traceback (most recent call last):
  File "/root/ThisIsScraper/this_is_scraper/scraper.py", line 126, in <module>
    main()
  File "/root/ThisIsScraper/this_is_scraper/scraper.py", line 121, in main
    process_pending_articles(db_sess)
  File "/root/ThisIsScraper/this_is_scraper/scraper.py", line 108, in process_pending_articles
    db_sess.commit()
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 921, in commit
    self.transaction.commit()
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 737, in _emit_update_statements
    execute(statement, multiparams)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/thisisscraper/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/thisisscraper/lib/python3.4/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/opt/thisisscraper/lib/python3.4/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/thisisscraper/lib/python3.4/site-packages/pymysql/connections.py", line 854, in query
    sql = sql.encode(self.encoding, 'surrogateescape')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 85: ordinal not in range(256)

**Comment by robputt** [comment]
Propose base 64 encoding content for storage?

**Comment by robputt** [comment]
Fixed, does not require base64 encoding of content, just don't use latin-1 character set in MySQL DB schema... When creating database use...

CREATE DATABASE thisisscraper CHARACTER SET utf8 COLLATE utf8_general_ci;

**Comment by robputt** [comment]
Add ?charset=utf8 to connection string in config.py too else pymysql defaults to latin-1!
